/**
 * Curated collections — bundled with the app (zero Firestore reads).
 * Generated by scripts/migrate-collections.mjs from the legacy per-game JSON.
 * Browsing curated content never touches the Spark quota.
 *
 * Units 0-3 completion pass (2026-07-01): 19 new decks added via
 * scripts/gen-new-decks.mjs — see docs/handoff/HANDOFF_NEXT_CLAUDE.md §4.9.
 */
import type { Collection } from "@/lib/collections/schema";

import weather from "./weather-letris.json";
import countries from "./countries-letris.json";
import nationalities from "./nationalities.json";
import languages from "./languages.json";
import lieux from "./lieux-letris.json";
import loinLesson from "./loin-lesson.json";
import directions from "./directions-matching.json";

import days from "./days.json";
import colors from "./colors.json";
import coreNouns from "./core-nouns.json";
import numbers020 from "./numbers-0-20.json";
import stressPronouns from "./stress-pronouns.json";
import professions from "./professions.json";
import matieres from "./matieres.json";
import numbers2069 from "./numbers-20-69.json";
import avoirEtats from "./avoir-etats.json";
import objetsArticles from "./objets-articles.json";
import possessives from "./possessives.json";
import aimerActivites from "./aimer-activites.json";
import faireActivites from "./faire-activites.json";
import allerDestinations from "./aller-destinations.json";
import quandTime from "./quand-time.json";
import avecQui from "./avec-qui.json";
import enAuAuxA from "./en-au-aux-a.json";
import questionWords from "./question-words.json";
import transport from "./transport.json";

import aliments from "./aliments.json";
import partitifs from "./partitifs.json";
import partitifNegatif from "./partitif-negatif.json";
import mangerBoire from "./manger-boire.json";
import frequence from "./frequence.json";
import demonstratifs from "./demonstratifs.json";
import commerces from "./commerces.json";
import modaux from "./modaux.json";

import etreEtudiant from "./etre-etudiant.json";
import parceQue from "./parce-que.json";
import vouloirInviter from "./vouloir-inviter.json";
import pouvoir from "./pouvoir.json";
import enviesBesoins from "./envies-besoins.json";

export const CURATED: Collection[] = [
  weather as Collection,
  countries as Collection,
  nationalities as Collection,
  languages as Collection,
  lieux as Collection,
  loinLesson as Collection,
  directions as Collection,
  days as Collection,
  colors as Collection,
  coreNouns as Collection,
  numbers020 as Collection,
  stressPronouns as Collection,
  professions as Collection,
  matieres as Collection,
  numbers2069 as Collection,
  avoirEtats as Collection,
  objetsArticles as Collection,
  possessives as Collection,
  aimerActivites as Collection,
  faireActivites as Collection,
  allerDestinations as Collection,
  quandTime as Collection,
  avecQui as Collection,
  enAuAuxA as Collection,
  questionWords as Collection,
  transport as Collection,
  aliments as Collection,
  partitifs as Collection,
  partitifNegatif as Collection,
  mangerBoire as Collection,
  frequence as Collection,
  demonstratifs as Collection,
  commerces as Collection,
  modaux as Collection,
  etreEtudiant as Collection,
  parceQue as Collection,
  vouloirInviter as Collection,
  pouvoir as Collection,
  enviesBesoins as Collection,
].sort((a, b) => (a.seq ?? 999) - (b.seq ?? 999));
