/**
 * 404 page.
 *
 * WHY THIS EXISTS: the app is a static export (`output: "export"` in
 * next.config.ts), so any URL outside the set generated by
 * generateStaticParams has no file behind it. Without this component the
 * result is not a friendly "not found" — it is a hard failure:
 *
 *   ⨯ Failed to generate static paths for /sio/[id]:
 *     Page "/sio/[id]/page" is missing param "/sio/[id]" in
 *     "generateStaticParams()", which is required with "output: export"
 *
 * Reproduced 2026-08-10 by opening /sio/SIO-059 (the SIO set stops at 050).
 * Any stale bookmark, shared link from an older build, or mistyped URL lands
 * here — including links to SIO-045, retired in the July re-cut, and to
 * `les-de` and `modaux`, both removed on 2026-08-09.
 *
 * Deliberately dependency-light: no auth, no Firestore, no progress read. A
 * 404 must render even when the thing that broke is one of those.
 */
import Link from "next/link";

export default function NotFound() {
  return (
    <main className="mx-auto flex min-h-[60vh] max-w-xl flex-col items-center justify-center gap-5 px-6 text-center">
      <p className="text-5xl" aria-hidden>
        🧭
      </p>

      <h1 className="cahier-hand cahier-display text-3xl font-normal text-[color:var(--cahier-ink)]">
        Page not found
      </h1>

      <p className="cahier-body text-sm leading-relaxed text-[color:var(--fluo-ink-soft)]">
        This page doesn&rsquo;t exist, or it has moved.
      </p>

      <div className="flex flex-wrap items-center justify-center gap-2">
        <Link href="/" className="fluo-btn">
          ▶ Home
        </Link>
        <Link href="/activities" className="cahier-btn">
          📖 <span lang="fr">Index</span>
        </Link>
      </div>

      <p className="cahier-body text-xs text-[color:var(--fluo-ink-soft)]">
        <span lang="en">
          If you followed a link from somewhere in the app, that&rsquo;s worth reporting — use the feedback
          button.
        </span>
      </p>
    </main>
  );
}
