/**
 * GramMarathon FINALE question bank — every item reviewed by Dan
 * (live red-pen sessions, 2026-07-20/21). Style guide R1-R6: one gap,
 * one word (apostrophes/inversion-hyphens split, compounds glue), unique
 * determination or declared alternates, no English shown (hint = category
 * label behind the lightbulb), interrogatives carry their reply.
 * GENERATED from the reviewed trial paper (finale-trial.html) — edit
 * items THERE first, then re-extract, so the reviewed artifact and the
 * shipped bank never drift.
 */

export type FinaleItem = {
  id: string; // finale:SIO-xxx:n
  sio: string;
  unit: number;
  pre: string;
  post: string;
  a: string[]; // accepted answers, primary first
  cat: string; // English category label shown on hint request
  strict?: boolean; // accent-strict grading (ou vs où)
};

export const FINALE_BANK: FinaleItem[] = [
  { id: "finale:SIO-001:1", sio: "SIO-001", unit: 0, pre: "— Bonjour ! Je m'", post: " Léo, et toi ? — Moi, c'est Emma !", a: ["appelle"], cat: "a conjugated verb" },
  { id: "finale:SIO-001:2", sio: "SIO-001", unit: 0, pre: "Ils s'", post: " Hugo et Nathan.", a: ["appellent"], cat: "a conjugated verb" },
  { id: "finale:SIO-002:1", sio: "SIO-002", unit: 0, pre: "— Madame, comment ", post: " appelez-vous ? — Je m'appelle Anne Martin.", a: ["vous"], cat: "a pronoun" },
  { id: "finale:SIO-002:2", sio: "SIO-002", unit: 0, pre: "— Salut Emma ! Tu ", post: " bien ? — Oui, très bien, merci !", a: ["vas"], cat: "a conjugated verb" },
  { id: "finale:SIO-003:1", sio: "SIO-003", unit: 0, pre: "— A : ", post: " ça s'écrit ? — B : Ça s'écrit F – A – B – I – E – N.", a: ["comment"], cat: "a question word" },
  { id: "finale:SIO-003:2", sio: "SIO-003", unit: 0, pre: "Mon prénom s'", post: " K – A – R – I – M.", a: ["écrit", "ecrit"], cat: "a conjugated verb" },
  { id: "finale:SIO-004:1", sio: "SIO-004", unit: 0, pre: "Demain, c'est vendredi. Aujourd'hui, c'est ", post: ".", a: ["jeudi"], cat: "a day of the week" },
  { id: "finale:SIO-004:2", sio: "SIO-004", unit: 0, pre: "Après le dîner samedi ", post: ", nous allons au cinéma.", a: ["soir"], cat: "a moment of the day" },
  { id: "finale:SIO-005:1", sio: "SIO-005", unit: 0, pre: "Le drapeau français est bleu, ", post: " et rouge.", a: ["blanc"], cat: "a colour" },
  { id: "finale:SIO-005:2", sio: "SIO-005", unit: 0, pre: "La nuit, le ciel est ", post: ".", a: ["noir"], cat: "a colour" },
  { id: "finale:SIO-006:1", sio: "SIO-006", unit: 0, pre: "— ", post: " est-ce ? — C'est mon professeur.", a: ["qui"], cat: "a question word" },
  { id: "finale:SIO-006:2", sio: "SIO-006", unit: 0, pre: "— ", post: " est-ce que c'est ? — C'est un stylo.", a: ["qu'", "qu"], cat: "a question word" },
  { id: "finale:SIO-007:1", sio: "SIO-007", unit: 0, pre: "Neuf plus six, ça fait ", post: ".", a: ["quinze"], cat: "a number" },
  { id: "finale:SIO-007:2", sio: "SIO-007", unit: 0, pre: "C'est mon anniversaire aujourd'hui : je n'ai plus dix-huit ans, j'ai ", post: " ans !", a: ["dix-neuf"], cat: "a number" },
  { id: "finale:SIO-008:1", sio: "SIO-008", unit: 0, pre: "— Les enfants, le livre est fermé ? — Oui, madame ! — Alors, ", post: "-le à la page douze !", a: ["ouvrez"], cat: "a classroom instruction" },
  { id: "finale:SIO-008:2", sio: "SIO-008", unit: 0, pre: "Je ne comprends pas. Vous pouvez ", post: ", s'il vous plaît ?", a: ["répéter", "repeter"], cat: "a verb in the infinitive" },
  { id: "finale:SIO-009:1", sio: "SIO-009", unit: 0, pre: "Il est 20 h. — ", post: ", madame !", a: ["bonsoir"], cat: "a greeting" },
  { id: "finale:SIO-009:2", sio: "SIO-009", unit: 0, pre: "Nous sommes jeudi. Le prochain cours est dans une semaine exactement. Au revoir et à ", post: " prochain !", a: ["jeudi"], cat: "a day of the week" },
  { id: "finale:SIO-010:1", sio: "SIO-010", unit: 0, pre: "— Je te présente Chloé. — ", post: " ! Moi, c'est Karim.", a: ["enchanté", "enchante"], cat: "a polite expression" },
  { id: "finale:SIO-010:2", sio: "SIO-010", unit: 0, pre: "C'", post: " mon amie : elle s'appelle Chloé.", a: ["est"], cat: "a presentative (c'est)" },
  { id: "finale:SIO-011:1", sio: "SIO-011", unit: 1, pre: "— Qui est étudiant ici ? — ", post: ", je suis étudiant !", a: ["moi"], cat: "a stressed pronoun" },
  { id: "finale:SIO-011:2", sio: "SIO-011", unit: 1, pre: "Tu parles de Hugo ? Oui, ", post: ", il est sympa.", a: ["lui"], cat: "a stressed pronoun" },
  { id: "finale:SIO-012:1", sio: "SIO-012", unit: 1, pre: "Il travaille à l'hôpital : il est ", post: ".", a: ["médecin", "medecin", "docteur", "infirmier"], cat: "a profession" },
  { id: "finale:SIO-012:2", sio: "SIO-012", unit: 1, pre: "Elle enseigne le français : elle est ", post: ".", a: ["professeure", "professeur", "prof"], cat: "a profession (feminine)" },
  { id: "finale:SIO-013:1", sio: "SIO-013", unit: 1, pre: "— Qu'est-ce que tu étudies ? — J'étudie ", post: " chimie.", a: ["la"], cat: "an article" },
  { id: "finale:SIO-013:2", sio: "SIO-013", unit: 1, pre: "J'aime les nombres et les calculs : j'étudie les ", post: ".", a: ["mathématiques", "mathematiques", "maths"], cat: "an academic subject" },
  { id: "finale:SIO-014:1", sio: "SIO-014", unit: 1, pre: "Nous ", post: " étudiants à l'université.", a: ["sommes"], cat: "a conjugated verb" },
  { id: "finale:SIO-014:2", sio: "SIO-014", unit: 1, pre: "Marie et Léa ", post: " étudiantes.", a: ["sont"], cat: "a conjugated verb" },
  { id: "finale:SIO-015:1", sio: "SIO-015", unit: 1, pre: "Paris est la capitale de ", post: " France.", a: ["la"], cat: "an article" },
  { id: "finale:SIO-015:2", sio: "SIO-015", unit: 1, pre: "— C'est quel pays ? Tokyo est sa capitale. — C'est ", post: " Japon.", a: ["le"], cat: "an article" },
  { id: "finale:SIO-016:1", sio: "SIO-016", unit: 1, pre: "Il vient du Portugal : il est ", post: ".", a: ["portugais"], cat: "a nationality" },
  { id: "finale:SIO-016:2", sio: "SIO-016", unit: 1, pre: "Elle vient d'Italie : elle est ", post: ".", a: ["italienne"], cat: "a nationality (feminine)" },
  { id: "finale:SIO-017:1", sio: "SIO-017", unit: 1, pre: "En Allemagne, on parle ", post: ".", a: ["allemand"], cat: "a language" },
  { id: "finale:SIO-017:2", sio: "SIO-017", unit: 1, pre: "À Singapour, on parle ", post: ".", a: ["anglais", "mandarin", "malais", "tamoul"], cat: "a language" },
  { id: "finale:SIO-018:1", sio: "SIO-018", unit: 1, pre: "Treize fois trois, ça fait ", post: ".", a: ["trente-neuf"], cat: "a number" },
  { id: "finale:SIO-018:2", sio: "SIO-018", unit: 1, pre: "Trente plus un, ça fait trente ", post: " un.", a: ["et"], cat: "a small linking word" },
  { id: "finale:SIO-019:1", sio: "SIO-019", unit: 1, pre: "— Quel âge as-tu ? — J'", post: " vingt ans.", a: ["ai"], cat: "a conjugated verb" },
  { id: "finale:SIO-019:2", sio: "SIO-019", unit: 1, pre: "Il est midi et je n'ai pas de sandwich : j'ai ", post: " !", a: ["faim"], cat: "a state (with avoir)" },
  { id: "finale:SIO-019:3", sio: "SIO-019", unit: 1, pre: "Le désert est très chaud : nous avons ", post: ".", a: ["soif", "chaud", "soif et chaud", "chaud et soif"], cat: "a state (with avoir)" },
  { id: "finale:SIO-020:1", sio: "SIO-020", unit: 1, pre: "Le Portugal est ", post: " Europe.", a: ["en"], cat: "a preposition" },
  { id: "finale:SIO-020:2", sio: "SIO-020", unit: 1, pre: "La France est en Europe ; ", post: " parle français ; la capitale est Paris.", a: ["on"], cat: "a pronoun" },
  { id: "finale:SIO-021:1", sio: "SIO-021", unit: 2, pre: "Voici un sac et un livre. Le sac ? C'est ", post: " sac de Marie.", a: ["le"], cat: "an article" },
  { id: "finale:SIO-021:2", sio: "SIO-021", unit: 2, pre: "— Qu'est-ce que c'est ? — Ce ", post: " des crayons.", a: ["sont"], cat: "a conjugated verb" },
  { id: "finale:SIO-022:1", sio: "SIO-022", unit: 2, pre: "J'ai une amie. Elle s'appelle Chloé : c'est ", post: " amie.", a: ["mon"], cat: "a possessive adjective" },
  { id: "finale:SIO-022:2", sio: "SIO-022", unit: 2, pre: "Hugo et Léa ont un chien : c'est ", post: " chien.", a: ["leur"], cat: "a possessive adjective" },
  { id: "finale:SIO-023:1", sio: "SIO-023", unit: 2, pre: "— Tu aimes le café ? — Oui, j'", post: " beaucoup le café !", a: ["aime"], cat: "a conjugated verb" },
  { id: "finale:SIO-023:2", sio: "SIO-023", unit: 2, pre: "— Vous aimez danser ? — Oui, nous ", post: " danser, surtout le week-end !", a: ["aimons", "adorons"], cat: "a conjugated verb" },
  { id: "finale:SIO-024:1", sio: "SIO-024", unit: 2, pre: "Elle adore nager : elle fait ", post: " la natation.", a: ["de"], cat: "a small word (contraction)" },
  { id: "finale:SIO-024:2", sio: "SIO-024", unit: 2, pre: "Il aime le sport : il fait ", post: " football le samedi.", a: ["du"], cat: "a contracted article" },
  { id: "finale:SIO-025:1", sio: "SIO-025", unit: 2, pre: "— Pourquoi tu étudies le français ? — ", post: " que c'est intéressant !", a: ["parce"], cat: "part of a linking phrase" },
  { id: "finale:SIO-025:2", sio: "SIO-025", unit: 2, pre: "— ", post: " tu aimes ce café ? — Parce que c'est délicieux.", a: ["pourquoi"], cat: "a question word" },
  { id: "finale:SIO-026:1", sio: "SIO-026", unit: 2, pre: "Le film commence ! Nous allons ", post: " cinéma.", a: ["au"], cat: "a contracted article" },
  { id: "finale:SIO-026:2", sio: "SIO-026", unit: 2, pre: "Elle va à ", post: " université en bus.", a: ["l'", "l"], cat: "an article (elided)" },
  { id: "finale:SIO-027:1", sio: "SIO-027", unit: 2, pre: "Je fais du yoga ", post: " les jours : lundi, mardi, mercredi, jeudi… sans exception !", a: ["tous"], cat: "a frequency word" },
  { id: "finale:SIO-027:2", sio: "SIO-027", unit: 2, pre: "Le cours commence ", post: " 9 h précises.", a: ["à", "a"], cat: "a preposition" },
  { id: "finale:SIO-028:1", sio: "SIO-028", unit: 2, pre: "Il n'y a pas ", post: " café dans le frigo.", a: ["de"], cat: "a small word (negation rule)" },
  { id: "finale:SIO-028:2", sio: "SIO-028", unit: 2, pre: "Je n'aime pas ", post: " thé, je préfère le café.", a: ["le"], cat: "an article (negation rule)" },
  { id: "finale:SIO-029:1", sio: "SIO-029", unit: 2, pre: "— Tu ", post: " manger avec nous ce soir ? — Oui, avec plaisir !", a: ["veux"], cat: "a conjugated verb" },
  { id: "finale:SIO-029:2", sio: "SIO-029", unit: 2, pre: "Je suis désolé, ce n'est pas possible : je ne ", post: " pas venir samedi. Dimanche, ça va ?", a: ["peux"], cat: "a conjugated verb" },
  { id: "finale:SIO-030:1", sio: "SIO-030", unit: 2, pre: "Demain, tu passes un examen. Bonne ", post: " !", a: ["chance"], cat: "a well-wish word" },
  { id: "finale:SIO-030:2", sio: "SIO-030", unit: 2, pre: "D'abord le petit-déjeuner, ", post: " le travail, enfin le cinéma.", a: ["ensuite", "puis"], cat: "a connector" },
  { id: "finale:SIO-031:1", sio: "SIO-031", unit: 3, pre: "— Quel temps fait-il ? — Il ", post: " : prends ton parapluie !", a: ["pleut"], cat: "a weather verb" },
  { id: "finale:SIO-031:2", sio: "SIO-031", unit: 3, pre: "En été à Singapour, il fait très ", post: ".", a: ["chaud", "beau", "mauvais"], cat: "a weather word" },
  { id: "finale:SIO-032:1", sio: "SIO-032", unit: 3, pre: "Elle habite à Tokyo : elle est ", post: " Japon.", a: ["au"], cat: "a preposition (masculine country)" },
  { id: "finale:SIO-032:2", sio: "SIO-032", unit: 3, pre: "Nous allons ", post: " France cet été.", a: ["en"], cat: "a preposition (feminine country)" },
  { id: "finale:SIO-033:1", sio: "SIO-033", unit: 3, pre: "J'ai faim ! Je vais ", post: " restaurant.", a: ["au"], cat: "a contracted article" },
  { id: "finale:SIO-033:2", sio: "SIO-033", unit: 3, pre: "Le train arrive : elle vient ", post: " la gare.", a: ["de", "à", "a"], cat: "a small word (preposition)" },
  { id: "finale:SIO-034:1", sio: "SIO-034", unit: 3, pre: "La banque est à ", post: " de la pharmacie — juste à gauche.", a: ["côté", "cote"], cat: "part of a spatial phrase" },
  { id: "finale:SIO-034:2", sio: "SIO-034", unit: 3, pre: "Le cinéma est en ", post: " de l'hôtel, de l'autre côté de la rue.", a: ["face"], cat: "part of a spatial phrase" },
  { id: "finale:SIO-035:1", sio: "SIO-035", unit: 3, pre: "— ", post: "-ce que tu parles français ? — Oui, un peu !", a: ["est"], cat: "part of a question phrase" },
  { id: "finale:SIO-035:2", sio: "SIO-035", unit: 3, pre: "— ", post: " est-ce que tu habites ? — À Clementi.", a: ["où"], cat: "a question word", strict: true },
  { id: "finale:SIO-036:1", sio: "SIO-036", unit: 3, pre: "Prenez la ", post: " rue à droite — la rue numéro un !", a: ["première", "premiere"], cat: "an ordinal number" },
  { id: "finale:SIO-036:2", sio: "SIO-036", unit: 3, pre: "Pour la gare, il ", post: " continuer tout droit.", a: ["faut", "peut", "doit", "va"], cat: "a conjugated verb" },
  { id: "finale:SIO-037:1", sio: "SIO-037", unit: 3, pre: "— On ", post: " nager ici ? — Oui, la piscine est ouverte !", a: ["peut", "va"], cat: "a conjugated verb" },
  { id: "finale:SIO-037:2", sio: "SIO-037", unit: 3, pre: "Vous ", post: " acheter les billets en ligne.", a: ["pouvez", "devez", "allez"], cat: "a conjugated verb" },
  { id: "finale:SIO-038:1", sio: "SIO-038", unit: 3, pre: "— Comment tu vas à l'université ? — Je ", post: " le bus 96.", a: ["prends"], cat: "a conjugated verb" },
  { id: "finale:SIO-038:2", sio: "SIO-038", unit: 3, pre: "— Tu vas souvent à la bibliothèque ? — Oui, j'", post: " vais tous les jours.", a: ["y"], cat: "a pronoun" },
  { id: "finale:SIO-039:1", sio: "SIO-039", unit: 3, pre: "Pour voyager, j'ai ", post: " d'un passeport.", a: ["besoin"], cat: "part of a need phrase" },
  { id: "finale:SIO-039:2", sio: "SIO-039", unit: 3, pre: "Au restaurant : « Je ", post: " un café, s'il vous plaît. »", a: ["voudrais", "commande"], cat: "a polite verb form" },
  { id: "finale:SIO-040:1", sio: "SIO-040", unit: 3, pre: "D'abord, prenez le métro ; ", post: ", marchez cinq minutes ; enfin, tournez à gauche.", a: ["puis", "ensuite"], cat: "a connector" },
  { id: "finale:SIO-040:2", sio: "SIO-040", unit: 3, pre: "D'abord Paris, puis Lyon, et ", post: ", Marseille — c'est la dernière étape !", a: ["enfin", "finalement"], cat: "a connector" },
  { id: "finale:SIO-041:1", sio: "SIO-041", unit: 4, pre: "Le matin, à 7 h, je prends le petit-", post: ".", a: ["déjeuner", "dejeuner"], cat: "a meal word" },
  { id: "finale:SIO-041:2", sio: "SIO-041", unit: 4, pre: "Une banane, une pomme, une orange : j'adore les ", post: " !", a: ["fruits"], cat: "a food category" },
  { id: "finale:SIO-042:1", sio: "SIO-042", unit: 4, pre: "Je mange ", post: " pain et du beurre au petit-déjeuner.", a: ["du"], cat: "a partitive article" },
  { id: "finale:SIO-042:2", sio: "SIO-042", unit: 4, pre: "Elle boit de ", post: " eau après le sport.", a: ["l'", "l"], cat: "an article (elided partitive)" },
  { id: "finale:SIO-043:1", sio: "SIO-043", unit: 4, pre: "Je mange du poisson une fois par semaine : je mange ", post: " du poisson.", a: ["parfois", "quelquefois", "souvent", "rarement"], cat: "a frequency adverb" },
  { id: "finale:SIO-043:2", sio: "SIO-043", unit: 4, pre: "Il boit du café tous les matins, sans exception : il boit ", post: " du café.", a: ["toujours"], cat: "a frequency adverb" },
  { id: "finale:SIO-044:1", sio: "SIO-044", unit: 4, pre: "On achète le pain à la ", post: ".", a: ["boulangerie"], cat: "a shop" },
  { id: "finale:SIO-044:2", sio: "SIO-044", unit: 4, pre: "Pour les médicaments, allez à la ", post: ".", a: ["pharmacie"], cat: "a shop" },
  { id: "finale:SIO-045:1", sio: "SIO-045", unit: 4, pre: "— Le client : « Ça fait ", post: " ? » — Le marchand : « Ça fait 6,50 €. »", a: ["combien"], cat: "a question word" },
  { id: "finale:SIO-045:2", sio: "SIO-045", unit: 4, pre: "— Je ", post: " deux kilos de pommes, s'il vous plaît.", a: ["voudrais"], cat: "a polite verb form" },
  { id: "finale:SIO-045A:1", sio: "SIO-045A", unit: 4, pre: "Soixante-dix plus dix, ça fait ", post: ".", a: ["quatre-vingts", "quatre vingts", "quatre-vingt", "quatre vingt"], cat: "a number" },
  { id: "finale:SIO-045A:2", sio: "SIO-045A", unit: 4, pre: "Ça fait ", post: " euros. (91 €)", a: ["quatre-vingt-onze"], cat: "a number" },
  { id: "finale:SIO-046:1", sio: "SIO-046", unit: 4, pre: "Regarde ", post: " pommes ! Elles sont belles, non ?", a: ["ces", "les"], cat: "a demonstrative" },
  { id: "finale:SIO-046:2", sio: "SIO-046", unit: 4, pre: "J'achète ", post: " fromage-là, le petit.", a: ["ce"], cat: "a demonstrative" },
  { id: "finale:SIO-047:1", sio: "SIO-047", unit: 4, pre: "Ce soir, nous ", post: " manger au restaurant. C'est décidé !", a: ["allons", "devons"], cat: "a conjugated verb (near future)" },
  { id: "finale:SIO-047:2", sio: "SIO-047", unit: 4, pre: "Demain, je vais ", post: " mes devoirs — promis !", a: ["faire", "rendre", "soumettre", "réviser", "reviser", "finir", "terminer"], cat: "a verb in the infinitive" },
  { id: "finale:SIO-048:1", sio: "SIO-048", unit: 4, pre: "Tu es fatigué : tu ", post: " dormir !", a: ["dois", "vas", "peux"], cat: "a conjugated verb" },
  { id: "finale:SIO-048:2", sio: "SIO-048", unit: 4, pre: "Pour être en forme, il ", post: " manger des légumes.", a: ["faut", "doit"], cat: "a conjugated verb" },
  { id: "finale:SIO-049:1", sio: "SIO-049", unit: 4, pre: "Ce restaurant est excellent : la cuisine est ", post: " ! (⭐⭐⭐⭐⭐)", a: ["délicieuse", "delicieuse", "excellente", "bonne", "géniale", "geniale", "exceptionnelle", "super", "formidable", "magnifique", "parfaite", "fantastique"], cat: "an adjective (feminine)" },
  { id: "finale:SIO-049:2", sio: "SIO-049", unit: 4, pre: "Le service est lent et le plat est froid : c'est un ", post: " restaurant. (⭐)", a: ["mauvais"], cat: "an adjective" },
  { id: "finale:SIO-050:1", sio: "SIO-050", unit: 4, pre: "À la fin du repas : « L'", post: ", s'il vous plaît ! »", a: ["addition"], cat: "a restaurant word" },
  { id: "finale:SIO-001:3", sio: "SIO-001", unit: 0, pre: "— Comment tu t'", post: " ? — Je m'appelle Nina.", a: ["appelles"], cat: "a conjugated verb" },
  { id: "finale:SIO-001:4", sio: "SIO-001", unit: 0, pre: "Nous nous ", post: " Chan et Lim.", a: ["appelons"], cat: "a conjugated verb" },
  { id: "finale:SIO-002:3", sio: "SIO-002", unit: 0, pre: "Au professeur, je dis « vous ». À mon ami, je dis « ", post: " ».", a: ["tu"], cat: "a pronoun" },
  { id: "finale:SIO-002:4", sio: "SIO-002", unit: 0, pre: "— Monsieur, ", post: " êtes professeur ? — Oui, c'est moi.", a: ["vous"], cat: "a pronoun" },
  { id: "finale:SIO-003:3", sio: "SIO-003", unit: 0, pre: "« Léa » s'écrit L – É – A : trois ", post: " seulement !", a: ["lettres"], cat: "a spelling word" },
  { id: "finale:SIO-003:4", sio: "SIO-003", unit: 0, pre: "— Ça s'écrit ", post: " un accent ? — Oui : é, accent aigu.", a: ["avec"], cat: "a small word" },
  { id: "finale:SIO-004:3", sio: "SIO-004", unit: 0, pre: "Après mercredi, c'est ", post: ".", a: ["jeudi"], cat: "a day of the week" },
  { id: "finale:SIO-004:4", sio: "SIO-004", unit: 0, pre: "Le matin, le midi, l'après-midi et le ", post: ".", a: ["soir"], cat: "a moment of the day" },
  { id: "finale:SIO-005:3", sio: "SIO-005", unit: 0, pre: "— De quelle couleur est le soleil ? — Il est ", post: ".", a: ["jaune"], cat: "a colour" },
  { id: "finale:SIO-005:4", sio: "SIO-005", unit: 0, pre: "— De quelle couleur est la tomate ? — Elle est ", post: ".", a: ["rouge"], cat: "a colour" },
  { id: "finale:SIO-006:3", sio: "SIO-006", unit: 0, pre: "— C'est ", post: " ? — C'est Léa, ma sœur.", a: ["qui"], cat: "a question word" },
  { id: "finale:SIO-006:4", sio: "SIO-006", unit: 0, pre: "— Qu'est-ce que c'", post: " ? — C'est une gomme.", a: ["est"], cat: "a conjugated verb" },
  { id: "finale:SIO-007:3", sio: "SIO-007", unit: 0, pre: "Dix plus dix, ça fait ", post: ".", a: ["vingt"], cat: "a number" },
  { id: "finale:SIO-007:4", sio: "SIO-007", unit: 0, pre: "Vingt moins six, ça fait ", post: ".", a: ["quatorze"], cat: "a number" },
  { id: "finale:SIO-008:3", sio: "SIO-008", unit: 0, pre: "— Vous parlez trop vite ! ", post: " lentement, s'il vous plaît.", a: ["parlez", "répétez", "repetez"], cat: "a classroom instruction" },
  { id: "finale:SIO-008:4", sio: "SIO-008", unit: 0, pre: "Le cours est fini : ", post: " vos livres !", a: ["fermez", "rangez", "prenez"], cat: "a classroom instruction" },
  { id: "finale:SIO-009:3", sio: "SIO-009", unit: 0, pre: "Il est 8 h du matin. — ", post: ", monsieur !", a: ["bonjour"], cat: "a greeting" },
  { id: "finale:SIO-009:4", sio: "SIO-009", unit: 0, pre: "On part : « Au ", post: " ! À lundi ! »", a: ["revoir"], cat: "a leave-taking word" },
  { id: "finale:SIO-010:3", sio: "SIO-010", unit: 0, pre: "— Je vous ", post: " Monsieur Tan. — Enchanté !", a: ["présente", "presente"], cat: "a conjugated verb" },
  { id: "finale:SIO-010:4", sio: "SIO-010", unit: 0, pre: "— Tu es Karim ? — Oui, c'est ", post: " !", a: ["moi"], cat: "a stressed pronoun" },
  { id: "finale:SIO-011:3", sio: "SIO-011", unit: 1, pre: "Nous, on étudie ; et ", post: ", vous travaillez.", a: ["vous"], cat: "a stressed pronoun" },
  { id: "finale:SIO-011:4", sio: "SIO-011", unit: 1, pre: "— C'est toi, Hugo ? — Oui, c'est ", post: " !", a: ["moi"], cat: "a stressed pronoun" },
  { id: "finale:SIO-012:3", sio: "SIO-012", unit: 1, pre: "Il éteint les incendies : il est ", post: ".", a: ["pompier"], cat: "a profession" },
  { id: "finale:SIO-012:4", sio: "SIO-012", unit: 1, pre: "Elle soigne les dents : elle est ", post: ".", a: ["dentiste"], cat: "a profession" },
  { id: "finale:SIO-013:3", sio: "SIO-013", unit: 1, pre: "Napoléon, 1789, les rois : j'étudie l'", post: ".", a: ["histoire"], cat: "an academic subject" },
  { id: "finale:SIO-013:4", sio: "SIO-013", unit: 1, pre: "— Qu'est-ce que tu étudies ? — J'étudie ", post: " droit.", a: ["le"], cat: "an article" },
  { id: "finale:SIO-014:3", sio: "SIO-014", unit: 1, pre: "Je ", post: " étudiant à NUS.", a: ["suis"], cat: "a conjugated verb" },
  { id: "finale:SIO-014:4", sio: "SIO-014", unit: 1, pre: "Vous ", post: " professeurs ?", a: ["êtes", "etes"], cat: "a conjugated verb" },
  { id: "finale:SIO-015:3", sio: "SIO-015", unit: 1, pre: "Rome est la capitale de l'", post: ".", a: ["italie"], cat: "a country" },
  { id: "finale:SIO-015:4", sio: "SIO-015", unit: 1, pre: "", post: " États-Unis sont en Amérique.", a: ["les"], cat: "an article" },
  { id: "finale:SIO-016:3", sio: "SIO-016", unit: 1, pre: "Il vient de France : il est ", post: ".", a: ["français", "francais"], cat: "a nationality" },
  { id: "finale:SIO-016:4", sio: "SIO-016", unit: 1, pre: "Elle vient du Japon : elle est ", post: ".", a: ["japonaise"], cat: "a nationality (feminine)" },
  { id: "finale:SIO-017:3", sio: "SIO-017", unit: 1, pre: "Au Mexique, on parle ", post: ".", a: ["espagnol"], cat: "a language" },
  { id: "finale:SIO-017:4", sio: "SIO-017", unit: 1, pre: "En Autriche, on parle ", post: ".", a: ["allemand"], cat: "a language" },
  { id: "finale:SIO-018:3", sio: "SIO-018", unit: 1, pre: "Vingt plus vingt, ça fait ", post: ".", a: ["quarante"], cat: "a number" },
  { id: "finale:SIO-018:4", sio: "SIO-018", unit: 1, pre: "Cinquante plus un, ça fait cinquante ", post: " un.", a: ["et"], cat: "a small linking word" },
  { id: "finale:SIO-019:4", sio: "SIO-019", unit: 1, pre: "Ils ", post: " vingt ans.", a: ["ont"], cat: "a conjugated verb" },
  { id: "finale:SIO-019:5", sio: "SIO-019", unit: 1, pre: "Il fait -5 °C et je n'ai pas de manteau : j'ai ", post: " !", a: ["froid"], cat: "a state (with avoir)" },
  { id: "finale:SIO-020:3", sio: "SIO-020", unit: 1, pre: "L'Italie est ", post: " Europe.", a: ["en"], cat: "a preposition" },
  { id: "finale:SIO-020:4", sio: "SIO-020", unit: 1, pre: "En Italie, ", post: " parle italien.", a: ["on"], cat: "a pronoun" },
  { id: "finale:SIO-021:3", sio: "SIO-021", unit: 2, pre: "— C'est un stylo ? — Non, ce ", post: " des stylos : il y en a trois !", a: ["sont"], cat: "a conjugated verb" },
  { id: "finale:SIO-021:4", sio: "SIO-021", unit: 2, pre: "— Qu'est-ce qu'il y a dans le sac ? — Il y a ", post: " cahier et une trousse.", a: ["un"], cat: "an article" },
  { id: "finale:SIO-022:3", sio: "SIO-022", unit: 2, pre: "Nous avons une voiture : c'est ", post: " voiture.", a: ["notre"], cat: "a possessive adjective" },
  { id: "finale:SIO-022:4", sio: "SIO-022", unit: 2, pre: "Tu as un vélo : c'est ", post: " vélo.", a: ["ton"], cat: "a possessive adjective" },
  { id: "finale:SIO-023:3", sio: "SIO-023", unit: 2, pre: "Elles ", post: " le chocolat.", a: ["aiment", "adorent", "détestent", "detestent", "préfèrent", "preferent"], cat: "a conjugated verb" },
  { id: "finale:SIO-023:4", sio: "SIO-023", unit: 2, pre: "Tu ", post: " chanter ?", a: ["aimes", "veux", "peux", "vas", "dois", "adores"], cat: "a conjugated verb" },
  { id: "finale:SIO-024:3", sio: "SIO-024", unit: 2, pre: "Elle fait ", post: " la danse.", a: ["de"], cat: "a small word (contraction)" },
  { id: "finale:SIO-024:4", sio: "SIO-024", unit: 2, pre: "Nous faisons ", post: " vélo.", a: ["du"], cat: "a contracted article" },
  { id: "finale:SIO-025:3", sio: "SIO-025", unit: 2, pre: "— Pourquoi tu manges ? — Parce que j'ai ", post: " !", a: ["faim"], cat: "a state (with avoir)" },
  { id: "finale:SIO-025:4", sio: "SIO-025", unit: 2, pre: "— Pourquoi tu aimes ce café ? — Parce que c'est ", post: " et il y a une belle terrasse !", a: ["sympa", "agréable", "agreable", "calme", "joli", "tranquille", "super", "génial", "genial", "bien", "beau"], cat: "an adjective" },
  { id: "finale:SIO-026:3", sio: "SIO-026", unit: 2, pre: "On va à ", post: " piscine ?", a: ["la"], cat: "an article" },
  { id: "finale:SIO-026:4", sio: "SIO-026", unit: 2, pre: "Ils vont ", post: " toilettes.", a: ["aux"], cat: "a contracted article" },
  { id: "finale:SIO-027:3", sio: "SIO-027", unit: 2, pre: "Je nage ", post: " week-end — tous les samedis et dimanches !", a: ["le"], cat: "an article (time use)" },
  { id: "finale:SIO-027:4", sio: "SIO-027", unit: 2, pre: "— À quelle heure mangez-vous ? — ", post: " midi.", a: ["à", "a", "vers"], cat: "a preposition" },
  { id: "finale:SIO-028:3", sio: "SIO-028", unit: 2, pre: "Je ne fais pas ", post: " sport.", a: ["de"], cat: "a small word (negation rule)" },
  { id: "finale:SIO-028:4", sio: "SIO-028", unit: 2, pre: "Elle n'aime pas ", post: " maths.", a: ["les"], cat: "an article (negation rule)" },
  { id: "finale:SIO-029:3", sio: "SIO-029", unit: 2, pre: "— On va au cinéma ? — Désolé, ce n'est pas possible : je ne ", post: " pas ce soir.", a: ["peux"], cat: "a conjugated verb" },
  { id: "finale:SIO-029:4", sio: "SIO-029", unit: 2, pre: "— Tu veux venir samedi ? — Oui, je ", post: " bien !", a: ["veux"], cat: "a conjugated verb" },
  { id: "finale:SIO-030:3", sio: "SIO-030", unit: 2, pre: "Il a 21 ans aujourd'hui : « Joyeux ", post: " ! »", a: ["anniversaire"], cat: "a well-wish word" },
  { id: "finale:SIO-030:4", sio: "SIO-030", unit: 2, pre: "D'abord Rome, ", post: " Florence, enfin Venise.", a: ["puis", "ensuite"], cat: "a connector" },
  { id: "finale:SIO-031:3", sio: "SIO-031", unit: 3, pre: "Il y a des nuages gris… il va ", post: " !", a: ["pleuvoir"], cat: "a weather verb (infinitive)" },
  { id: "finale:SIO-031:4", sio: "SIO-031", unit: 3, pre: "En hiver au Canada, il fait très ", post: ".", a: ["froid", "mauvais", "beau"], cat: "a weather word" },
  { id: "finale:SIO-032:3", sio: "SIO-032", unit: 3, pre: "Il habite à Lisbonne, ", post: " Portugal.", a: ["au"], cat: "a preposition (masculine country)" },
  { id: "finale:SIO-032:4", sio: "SIO-032", unit: 3, pre: "Elles vont ", post: " États-Unis.", a: ["aux"], cat: "a preposition (plural country)" },
  { id: "finale:SIO-033:3", sio: "SIO-033", unit: 3, pre: "On achète des livres à ", post: " librairie.", a: ["la"], cat: "an article" },
  { id: "finale:SIO-033:4", sio: "SIO-033", unit: 3, pre: "Le film est fini : il sort ", post: " cinéma à 22 h.", a: ["du"], cat: "a contracted article" },
  { id: "finale:SIO-034:3", sio: "SIO-034", unit: 3, pre: "Le café est ", post: " de la banque — 200 mètres seulement.", a: ["près", "pres"], cat: "part of a spatial phrase" },
  { id: "finale:SIO-034:4", sio: "SIO-034", unit: 3, pre: "J'habite ", post: " du centre : une heure de bus !", a: ["loin"], cat: "part of a spatial phrase" },
  { id: "finale:SIO-035:3", sio: "SIO-035", unit: 3, pre: "— ", post: " est-ce que tu manges à midi ? — Un sandwich.", a: ["qu'", "qu"], cat: "a question word" },
  { id: "finale:SIO-035:4", sio: "SIO-035", unit: 3, pre: "— ", post: " est-ce que le cours commence ? — À 9 h.", a: ["quand"], cat: "a question word" },
  { id: "finale:SIO-036:3", sio: "SIO-036", unit: 3, pre: "Prenez la ", post: " rue à gauche — la rue numéro deux.", a: ["deuxième", "deuxieme"], cat: "an ordinal number" },
  { id: "finale:SIO-036:4", sio: "SIO-036", unit: 3, pre: "Il faut ", post: " tout droit, puis tourner.", a: ["continuer", "aller", "marcher"], cat: "a verb in the infinitive" },
  { id: "finale:SIO-037:3", sio: "SIO-037", unit: 3, pre: "Je ", post: " payer par carte ?", a: ["peux", "dois", "vais"], cat: "a conjugated verb" },
  { id: "finale:SIO-037:4", sio: "SIO-037", unit: 3, pre: "Ici, on ne ", post: " pas fumer.", a: ["peut", "doit"], cat: "a conjugated verb" },
  { id: "finale:SIO-038:3", sio: "SIO-038", unit: 3, pre: "Pour aller à Sentosa, on ", post: " le monorail.", a: ["prend"], cat: "a conjugated verb" },
  { id: "finale:SIO-038:4", sio: "SIO-038", unit: 3, pre: "— Tu connais ce café ? — Oui, j'", post: " vais souvent !", a: ["y"], cat: "a pronoun" },
  { id: "finale:SIO-039:3", sio: "SIO-039", unit: 3, pre: "Il fait froid : j'ai ", post: " d'un manteau.", a: ["besoin", "envie"], cat: "part of a need phrase" },
  { id: "finale:SIO-039:4", sio: "SIO-039", unit: 3, pre: "Un jour, j'", post: " visiter le Japon.", a: ["aimerais"], cat: "a polite verb form" },
  { id: "finale:SIO-040:3", sio: "SIO-040", unit: 3, pre: "On visite le temple ; ", post: ", le jardin ; enfin, le marché.", a: ["ensuite", "puis"], cat: "a connector" },
  { id: "finale:SIO-040:4", sio: "SIO-040", unit: 3, pre: "La ", post: " étape : l'aéroport. C'est la fin du voyage !", a: ["dernière", "derniere"], cat: "an adjective (ordinal)" },
  { id: "finale:SIO-041:3", sio: "SIO-041", unit: 4, pre: "À midi, je mange : c'est le ", post: ".", a: ["déjeuner", "dejeuner"], cat: "a meal word" },
  { id: "finale:SIO-041:4", sio: "SIO-041", unit: 4, pre: "Le soir, à 19 h, nous prenons le ", post: ".", a: ["dîner", "diner"], cat: "a meal word" },
  { id: "finale:SIO-042:3", sio: "SIO-042", unit: 4, pre: "Au petit-déjeuner, il mange ", post: " fromage et du pain.", a: ["du"], cat: "a partitive article" },
  { id: "finale:SIO-042:4", sio: "SIO-042", unit: 4, pre: "Tu veux de ", post: " salade ?", a: ["la"], cat: "an article (partitive)" },
  { id: "finale:SIO-043:3", sio: "SIO-043", unit: 4, pre: "Zéro fois par semaine : il ne mange ", post: " de viande.", a: ["jamais", "pas"], cat: "a frequency adverb" },
  { id: "finale:SIO-043:4", sio: "SIO-043", unit: 4, pre: "Sept jours sur sept, elle boit du thé : elle boit du thé ", post: " les jours.", a: ["tous"], cat: "a frequency word" },
  { id: "finale:SIO-044:3", sio: "SIO-044", unit: 4, pre: "On achète la viande à la ", post: ".", a: ["boucherie"], cat: "a shop" },
  { id: "finale:SIO-044:4", sio: "SIO-044", unit: 4, pre: "On achète les fruits frais au ", post: ".", a: ["marché", "marche", "supermarché", "supermarche"], cat: "a shop" },
  { id: "finale:SIO-045:3", sio: "SIO-045", unit: 4, pre: "— Et avec ", post: " ? — C'est tout, merci !", a: ["ceci", "ça", "ca"], cat: "a market formula word" },
  { id: "finale:SIO-045:4", sio: "SIO-045", unit: 4, pre: "— C'est ", post: ", merci ! — Au revoir !", a: ["tout", "bon"], cat: "a market formula word" },
  { id: "finale:SIO-045A:3", sio: "SIO-045A", unit: 4, pre: "Quatre-vingts plus dix, ça fait ", post: ".", a: ["quatre-vingt-dix"], cat: "a number" },
  { id: "finale:SIO-045A:4", sio: "SIO-045A", unit: 4, pre: "Ça fait ", post: " euros. (75 €)", a: ["soixante-quinze"], cat: "a number" },
  { id: "finale:SIO-046:3", sio: "SIO-046", unit: 4, pre: "", post: " homme, là-bas, c'est mon professeur.", a: ["cet", "l'", "l"], cat: "a demonstrative (before vowel)" },
  { id: "finale:SIO-046:4", sio: "SIO-046", unit: 4, pre: "Regarde la vitrine ! J'adore ", post: " chaussures-là !", a: ["ces"], cat: "a demonstrative (plural)" },
  { id: "finale:SIO-047:3", sio: "SIO-047", unit: 4, pre: "Demain, elle ", post: " visiter le musée.", a: ["va", "veut", "doit", "peut"], cat: "a conjugated verb (near future)" },
  { id: "finale:SIO-047:4", sio: "SIO-047", unit: 4, pre: "Ce week-end, ils vont ", post: " au football.", a: ["jouer"], cat: "a verb in the infinitive" },
  { id: "finale:SIO-048:3", sio: "SIO-048", unit: 4, pre: "Il est minuit : les enfants ", post: " dormir !", a: ["doivent", "vont", "peuvent"], cat: "a conjugated verb" },
  { id: "finale:SIO-048:4", sio: "SIO-048", unit: 4, pre: "Pour le visa, il ", post: " un passeport.", a: ["faut"], cat: "a conjugated verb" },
  { id: "finale:SIO-049:3", sio: "SIO-049", unit: 4, pre: "Service rapide, plats chauds : c'est un ", post: " restaurant ! (⭐⭐⭐⭐⭐)", a: ["bon", "excellent", "très bon", "super", "génial", "genial", "formidable", "magnifique", "parfait", "fantastique"], cat: "an adjective" },
  { id: "finale:SIO-049:4", sio: "SIO-049", unit: 4, pre: "200 € pour une salade ! C'est trop ", post: " !", a: ["cher"], cat: "an adjective" },
  { id: "finale:SIO-050:2", sio: "SIO-050", unit: 4, pre: "Le serveur : « Vous voulez commander ? » — « Oui, je ", post: " le poulet, s'il vous plaît. »", a: ["prends", "voudrais"], cat: "a conjugated verb" },
  { id: "finale:SIO-050:3", sio: "SIO-050", unit: 4, pre: "Le serveur : « Et comme ", post: " ? » — « De l'eau, s'il vous plaît. »", a: ["boisson"], cat: "a restaurant word" },
  { id: "finale:SIO-001:5", sio: "SIO-001", unit: 0, pre: "Elle s'", post: " Fatima.", a: ["appelle"], cat: "a conjugated verb" },
  { id: "finale:SIO-001:6", sio: "SIO-001", unit: 0, pre: "— Vous vous ", post: " comment ? — Diallo, Amadou Diallo.", a: ["appelez"], cat: "a conjugated verb" },
  { id: "finale:SIO-002:5", sio: "SIO-002", unit: 0, pre: "À un enfant, on dit « tu » ; à un client, on dit « ", post: " ».", a: ["vous"], cat: "a pronoun" },
  { id: "finale:SIO-002:6", sio: "SIO-002", unit: 0, pre: "— Salut Paul ! ", post: " es en forme ?", a: ["tu"], cat: "a pronoun" },
  { id: "finale:SIO-003:5", sio: "SIO-003", unit: 0, pre: "L'alphabet français a vingt-six ", post: ".", a: ["lettres"], cat: "a spelling word" },
  { id: "finale:SIO-003:6", sio: "SIO-003", unit: 0, pre: "Le mot « café », ça s'écrit avec un ", post: " accent aigu.", a: ["e"], cat: "a letter" },
  { id: "finale:SIO-004:5", sio: "SIO-004", unit: 0, pre: "Samedi et dimanche : c'est le ", post: " !", a: ["week-end", "weekend"], cat: "a time word" },
  { id: "finale:SIO-004:6", sio: "SIO-004", unit: 0, pre: "Le premier jour de la semaine en France, c'est ", post: ".", a: ["lundi"], cat: "a day of the week" },
  { id: "finale:SIO-005:5", sio: "SIO-005", unit: 0, pre: "— De quelle couleur est le pain ? — Il est ", post: ".", a: ["blanc", "marron", "beige", "jaune", "gris"], cat: "a colour" },
  { id: "finale:SIO-005:6", sio: "SIO-005", unit: 0, pre: "— De quelle couleur est le citron ? — Il est ", post: ".", a: ["jaune", "vert"], cat: "a colour" },
  { id: "finale:SIO-006:5", sio: "SIO-006", unit: 0, pre: "— Qui ", post: "-ce ? — C'est le professeur.", a: ["est"], cat: "a conjugated verb" },
  { id: "finale:SIO-006:6", sio: "SIO-006", unit: 0, pre: "— C'est un stylo ? — Non, c'est ", post: " crayon.", a: ["un"], cat: "an article" },
  { id: "finale:SIO-007:5", sio: "SIO-007", unit: 0, pre: "Trois fois quatre, ça fait ", post: ".", a: ["douze"], cat: "a number" },
  { id: "finale:SIO-007:6", sio: "SIO-007", unit: 0, pre: "Dix-sept moins dix, ça fait ", post: ".", a: ["sept"], cat: "a number" },
  { id: "finale:SIO-008:5", sio: "SIO-008", unit: 0, pre: "Prenez un stylo et ", post: " la phrase.", a: ["écrivez", "ecrivez", "copiez"], cat: "a classroom instruction" },
  { id: "finale:SIO-008:6", sio: "SIO-008", unit: 0, pre: "Je répète la question pour tout le monde : ", post: " bien !", a: ["écoutez", "ecoutez"], cat: "a classroom instruction" },
  { id: "finale:SIO-009:5", sio: "SIO-009", unit: 0, pre: "Minuit ! Je vais dormir : « Bonne ", post: " ! »", a: ["nuit"], cat: "a leave-taking word" },
  { id: "finale:SIO-009:6", sio: "SIO-009", unit: 0, pre: "— Merci beaucoup ! — De ", post: " !", a: ["rien"], cat: "a polite expression" },
  { id: "finale:SIO-010:5", sio: "SIO-010", unit: 0, pre: "— Salut, moi c'est Léo. Et ", post: " ?", a: ["toi"], cat: "a stressed pronoun" },
  { id: "finale:SIO-010:6", sio: "SIO-010", unit: 0, pre: "Voici Anna : ", post: " est étudiante en droit.", a: ["elle"], cat: "a pronoun" },
  { id: "finale:SIO-011:5", sio: "SIO-011", unit: 1, pre: "— Qui parle ? Emma ? — Oui, c'est ", post: ".", a: ["elle"], cat: "a stressed pronoun" },
  { id: "finale:SIO-011:6", sio: "SIO-011", unit: 1, pre: "Tu viens avec ", post: " ? Nous allons au parc.", a: ["nous"], cat: "a stressed pronoun" },
  { id: "finale:SIO-012:5", sio: "SIO-012", unit: 1, pre: "Il fait et il vend du pain et des croissants : il est ", post: ".", a: ["boulanger"], cat: "a profession" },
  { id: "finale:SIO-012:6", sio: "SIO-012", unit: 1, pre: "Elle joue dans des films : elle est ", post: ".", a: ["actrice", "comédienne", "comedienne"], cat: "a profession (feminine)" },
  { id: "finale:SIO-013:5", sio: "SIO-013", unit: 1, pre: "Les plantes, les animaux, le corps humain — ma matière préférée, c'est la ", post: " !", a: ["biologie"], cat: "an academic subject" },
  { id: "finale:SIO-013:6", sio: "SIO-013", unit: 1, pre: "J'étudie ", post: " économie à NUS.", a: ["l'", "l"], cat: "an article (elided)" },
  { id: "finale:SIO-014:5", sio: "SIO-014", unit: 1, pre: "Tu ", post: " français ?", a: ["es", "parles"], cat: "a conjugated verb" },
  { id: "finale:SIO-014:6", sio: "SIO-014", unit: 1, pre: "Elle ", post: " étudiante en chimie.", a: ["est"], cat: "a conjugated verb" },
  { id: "finale:SIO-015:5", sio: "SIO-015", unit: 1, pre: "Berlin ? C'est la capitale de l'", post: ".", a: ["allemagne"], cat: "a country" },
  { id: "finale:SIO-015:6", sio: "SIO-015", unit: 1, pre: "Cet été, je visite ", post: " Portugal.", a: ["le"], cat: "an article" },
  { id: "finale:SIO-016:5", sio: "SIO-016", unit: 1, pre: "Ils viennent d'Espagne : ils sont ", post: ".", a: ["espagnols"], cat: "a nationality (plural)" },
  { id: "finale:SIO-016:6", sio: "SIO-016", unit: 1, pre: "Elle vient de Chine : elle est ", post: ".", a: ["chinoise"], cat: "a nationality (feminine)" },
  { id: "finale:SIO-017:5", sio: "SIO-017", unit: 1, pre: "Au Canada, on parle anglais et ", post: ".", a: ["français", "francais"], cat: "a language" },
  { id: "finale:SIO-017:6", sio: "SIO-017", unit: 1, pre: "En Égypte, on parle ", post: ".", a: ["arabe"], cat: "a language" },
  { id: "finale:SIO-018:5", sio: "SIO-018", unit: 1, pre: "Trente plus trente, ça fait ", post: ".", a: ["soixante"], cat: "a number" },
  { id: "finale:SIO-018:6", sio: "SIO-018", unit: 1, pre: "Soixante moins dix, ça fait ", post: ".", a: ["cinquante"], cat: "a number" },
  { id: "finale:SIO-019:6", sio: "SIO-019", unit: 1, pre: "Nous ", post: " un examen demain.", a: ["avons", "passons"], cat: "a conjugated verb" },
  { id: "finale:SIO-019:7", sio: "SIO-019", unit: 1, pre: "Il est minuit. J'ai envie de dormir. Je suis ", post: ".", a: ["fatigué", "fatigue"], cat: "a state (with être)" },
  { id: "finale:SIO-020:5", sio: "SIO-020", unit: 1, pre: "Le Japon est ", post: " Asie.", a: ["en"], cat: "a preposition" },
  { id: "finale:SIO-020:6", sio: "SIO-020", unit: 1, pre: "La capitale du Japon, c'", post: " Tokyo.", a: ["est"], cat: "a conjugated verb" },
  { id: "finale:SIO-021:5", sio: "SIO-021", unit: 2, pre: "— Qu'est-ce que c'est ? — Ce sont ", post: " livres de français.", a: ["des"], cat: "an article" },
  { id: "finale:SIO-021:6", sio: "SIO-021", unit: 2, pre: "— À qui est ce téléphone ? — C'est ", post: " téléphone de Paul.", a: ["le"], cat: "an article" },
  { id: "finale:SIO-022:5", sio: "SIO-022", unit: 2, pre: "Elle a des chats : ce sont ", post: " chats.", a: ["ses"], cat: "a possessive adjective" },
  { id: "finale:SIO-022:6", sio: "SIO-022", unit: 2, pre: "Vous avez une maison : c'est ", post: " maison.", a: ["votre"], cat: "a possessive adjective" },
  { id: "finale:SIO-023:5", sio: "SIO-023", unit: 2, pre: "Il ", post: " la musique classique.", a: ["aime", "adore", "déteste", "deteste", "préfère", "prefere"], cat: "a conjugated verb" },
  { id: "finale:SIO-023:6", sio: "SIO-023", unit: 2, pre: "Vous ", post: " voyager ?", a: ["aimez"], cat: "a conjugated verb" },
  { id: "finale:SIO-024:5", sio: "SIO-024", unit: 2, pre: "Ils font de ", post: " escalade.", a: ["l'", "l"], cat: "an article (elided)" },
  { id: "finale:SIO-024:6", sio: "SIO-024", unit: 2, pre: "Je fais de ", post: " natation.", a: ["la"], cat: "an article" },
  { id: "finale:SIO-025:5", sio: "SIO-025", unit: 2, pre: "— Pourquoi tu étudies ? — ", post: " que j'aime apprendre.", a: ["parce"], cat: "part of a linking phrase" },
  { id: "finale:SIO-025:6", sio: "SIO-025", unit: 2, pre: "— Pourquoi tu restes ? — Parce ", post: " c'est intéressant.", a: ["que"], cat: "part of a linking phrase" },
  { id: "finale:SIO-026:5", sio: "SIO-026", unit: 2, pre: "J'ai faim : je vais ", post: " marché.", a: ["au"], cat: "a contracted article" },
  { id: "finale:SIO-026:6", sio: "SIO-026", unit: 2, pre: "Elle va à ", post: " plage dimanche.", a: ["la"], cat: "an article" },
  { id: "finale:SIO-027:5", sio: "SIO-027", unit: 2, pre: "", post: " lundi, j'ai cours de français.", a: ["le", "ce"], cat: "an article (time use)" },
  { id: "finale:SIO-027:6", sio: "SIO-027", unit: 2, pre: "Ils travaillent tous ", post: " jours.", a: ["les"], cat: "an article" },
  { id: "finale:SIO-028:5", sio: "SIO-028", unit: 2, pre: "Il n'y a pas ", post: " lait dans le frigo.", a: ["de"], cat: "a small word (negation rule)" },
  { id: "finale:SIO-028:6", sio: "SIO-028", unit: 2, pre: "Nous n'aimons pas ", post: " café froid.", a: ["le", "ce"], cat: "an article (negation rule)" },
  { id: "finale:SIO-029:5", sio: "SIO-029", unit: 2, pre: "Vous ", post: " danser avec nous ?", a: ["voulez", "pouvez", "aimez", "venez", "allez"], cat: "a conjugated verb" },
  { id: "finale:SIO-029:6", sio: "SIO-029", unit: 2, pre: "Désolé, ce n'est pas possible : nous ne ", post: " pas venir lundi. Mardi, ça va ?", a: ["pouvons"], cat: "a conjugated verb" },
  { id: "finale:SIO-030:5", sio: "SIO-030", unit: 2, pre: "Tu pars en France demain : « Bon ", post: " ! »", a: ["voyage"], cat: "a well-wish word" },
  { id: "finale:SIO-030:6", sio: "SIO-030", unit: 2, pre: "On mange ! « Bon ", post: " ! »", a: ["appétit", "appetit"], cat: "a well-wish word" },
  { id: "finale:SIO-031:5", sio: "SIO-031", unit: 3, pre: "Le soleil brille, pas un nuage : il fait ", post: " !", a: ["beau", "chaud"], cat: "a weather word" },
  { id: "finale:SIO-031:6", sio: "SIO-031", unit: 3, pre: "Le drapeau bouge, les feuilles volent : il y a du ", post: ".", a: ["vent"], cat: "a weather word" },
  { id: "finale:SIO-032:5", sio: "SIO-032", unit: 3, pre: "Nous venons ", post: " Singapour.", a: ["de"], cat: "a preposition" },
  { id: "finale:SIO-032:6", sio: "SIO-032", unit: 3, pre: "Il est ", post: " Chine pour le travail.", a: ["en"], cat: "a preposition (feminine country)" },
  { id: "finale:SIO-033:5", sio: "SIO-033", unit: 3, pre: "Elle est à ", post: " hôpital, elle est médecin.", a: ["l'", "l"], cat: "an article (elided)" },
  { id: "finale:SIO-033:6", sio: "SIO-033", unit: 3, pre: "À 18 h, nous rentrons ", post: " bureau.", a: ["du", "au"], cat: "a contracted article" },
  { id: "finale:SIO-034:5", sio: "SIO-034", unit: 3, pre: "La poste ? Juste à ", post: " de la mairie, porte à porte.", a: ["côté", "cote"], cat: "part of a spatial phrase" },
  { id: "finale:SIO-034:6", sio: "SIO-034", unit: 3, pre: "Le parking est en ", post: " du supermarché, de l'autre côté.", a: ["face"], cat: "part of a spatial phrase" },
  { id: "finale:SIO-035:5", sio: "SIO-035", unit: 3, pre: "— ", post: " est-ce que tu viens ? — En métro.", a: ["comment"], cat: "a question word" },
  { id: "finale:SIO-035:6", sio: "SIO-035", unit: 3, pre: "— Est-", post: " que vous parlez anglais ? — Oui.", a: ["ce"], cat: "part of a question phrase" },
  { id: "finale:SIO-036:5", sio: "SIO-036", unit: 3, pre: "C'est la ", post: " fois que je visite Paris : numéro trois !", a: ["troisième", "troisieme"], cat: "an ordinal number" },
  { id: "finale:SIO-036:6", sio: "SIO-036", unit: 3, pre: "Pour le musée, ", post: " prend la rue Victor-Hugo.", a: ["on"], cat: "a pronoun" },
  { id: "finale:SIO-037:5", sio: "SIO-037", unit: 3, pre: "Tu ", post: " m'aider, s'il te plaît ?", a: ["peux", "veux"], cat: "a conjugated verb" },
  { id: "finale:SIO-037:6", sio: "SIO-037", unit: 3, pre: "La porte est ouverte : nous ", post: " entrer ?", a: ["pouvons"], cat: "a conjugated verb" },
  { id: "finale:SIO-038:5", sio: "SIO-038", unit: 3, pre: "Vous ", post: " le taxi ou le bus ?", a: ["prenez", "préférez", "preferez"], cat: "a conjugated verb" },
  { id: "finale:SIO-038:6", sio: "SIO-038", unit: 3, pre: "La plage ? Nous ", post: " allons dimanche !", a: ["y"], cat: "a pronoun" },
  { id: "finale:SIO-039:5", sio: "SIO-039", unit: 3, pre: "Pour payer, j'ai besoin ", post: "argent.", a: ["d'", "d"], cat: "a small word (elided)" },
  { id: "finale:SIO-039:6", sio: "SIO-039", unit: 3, pre: "Elle ", post: " devenir médecin.", a: ["veut", "va", "doit", "peut"], cat: "a conjugated verb" },
  { id: "finale:SIO-040:5", sio: "SIO-040", unit: 3, pre: "Premièrement le musée, ", post: " le déjeuner.", a: ["puis", "ensuite", "deuxièmement", "deuxiemement"], cat: "a connector" },
  { id: "finale:SIO-040:6", sio: "SIO-040", unit: 3, pre: "Pour finir : ", post: ", on rentre à l'hôtel.", a: ["enfin", "finalement"], cat: "a connector" },
  { id: "finale:SIO-041:5", sio: "SIO-041", unit: 4, pre: "La carotte et la tomate sont des ", post: ".", a: ["légumes", "legumes"], cat: "a food category" },
  { id: "finale:SIO-041:6", sio: "SIO-041", unit: 4, pre: "Le matin, je bois un ", post: " au lait.", a: ["café", "cafe", "chocolat", "thé", "the"], cat: "a drink" },
  { id: "finale:SIO-042:5", sio: "SIO-042", unit: 4, pre: "Je bois ", post: " jus d'orange et de l'eau.", a: ["du"], cat: "a partitive article" },
  { id: "finale:SIO-042:6", sio: "SIO-042", unit: 4, pre: "Elle mange de ", post: " omelette.", a: ["l'", "l"], cat: "an article (elided partitive)" },
  { id: "finale:SIO-043:5", sio: "SIO-043", unit: 4, pre: "Une ou deux fois par mois seulement : je vais ", post: " au cinéma.", a: ["parfois", "rarement", "quelquefois"], cat: "a frequency adverb" },
  { id: "finale:SIO-043:6", sio: "SIO-043", unit: 4, pre: "Cinq fois par semaine ? C'est ", post: " !", a: ["souvent", "beaucoup"], cat: "a frequency adverb" },
  { id: "finale:SIO-044:5", sio: "SIO-044", unit: 4, pre: "Les gâteaux et les croissants ? À la ", post: " !", a: ["pâtisserie", "patisserie", "boulangerie"], cat: "a shop" },
  { id: "finale:SIO-044:6", sio: "SIO-044", unit: 4, pre: "On trouve tout — pain, lait, fruits — au ", post: ".", a: ["supermarché", "supermarche"], cat: "a shop" },
  { id: "finale:SIO-045:5", sio: "SIO-045", unit: 4, pre: "Le marchand : « Bonjour ! Vous ", post: " ? » — « Deux kilos de tomates. »", a: ["désirez", "desirez", "voulez"], cat: "a conjugated verb" },
  { id: "finale:SIO-045:6", sio: "SIO-045", unit: 4, pre: "— Ça ", post: " 7,80 €, s'il vous plaît.", a: ["fait", "coûte", "coute"], cat: "a conjugated verb" },
  { id: "finale:SIO-045A:5", sio: "SIO-045A", unit: 4, pre: "Soixante et onze plus un, ça fait ", post: ".", a: ["soixante-douze"], cat: "a number" },
  { id: "finale:SIO-045A:6", sio: "SIO-045A", unit: 4, pre: "Ça fait ", post: " euros. (88 €)", a: ["quatre-vingt-huit"], cat: "a number" },
  { id: "finale:SIO-046:5", sio: "SIO-046", unit: 4, pre: "", post: " tarte est délicieuse !", a: ["cette"], cat: "a demonstrative (feminine)" },
  { id: "finale:SIO-046:6", sio: "SIO-046", unit: 4, pre: "Tu vois ", post: " arbre-là ?", a: ["cet"], cat: "a demonstrative (before vowel)" },
  { id: "finale:SIO-047:5", sio: "SIO-047", unit: 4, pre: "Après le cours, nous ", post: " manger ensemble.", a: ["allons", "voulons", "devons", "pouvons"], cat: "a conjugated verb (near future)" },
  { id: "finale:SIO-047:6", sio: "SIO-047", unit: 4, pre: "Mes valises sont prêtes : demain matin, je vais ", post: " pour la France !", a: ["partir"], cat: "a verb in the infinitive" },
  { id: "finale:SIO-048:5", sio: "SIO-048", unit: 4, pre: "Examen demain : nous ", post: " étudier ce soir !", a: ["devons", "allons"], cat: "a conjugated verb" },
  { id: "finale:SIO-048:6", sio: "SIO-048", unit: 4, pre: "Tu ne peux pas entrer : il ", post: " un billet.", a: ["faut"], cat: "a conjugated verb" },
  { id: "finale:SIO-049:5", sio: "SIO-049", unit: 4, pre: "La soupe est froide… quelle ", post: " surprise ! (⭐)", a: ["mauvaise"], cat: "an adjective (feminine)" },
  { id: "finale:SIO-049:6", sio: "SIO-049", unit: 4, pre: "Cinq étoiles : je ", post: " ce restaurant à tous mes amis !", a: ["recommande"], cat: "a conjugated verb" },
  { id: "finale:SIO-050:4", sio: "SIO-050", unit: 4, pre: "« Une ", post: " pour quatre personnes, s'il vous plaît. »", a: ["table"], cat: "a restaurant word" },
  { id: "finale:SIO-050:5", sio: "SIO-050", unit: 4, pre: "À la fin : « Vous pouvez payer par ", post: " ou en espèces. »", a: ["carte"], cat: "a restaurant word" },
];

export const FINALE_SIOS: string[] = ["SIO-001", "SIO-002", "SIO-003", "SIO-004", "SIO-005", "SIO-006", "SIO-007", "SIO-008", "SIO-009", "SIO-010", "SIO-011", "SIO-012", "SIO-013", "SIO-014", "SIO-015", "SIO-016", "SIO-017", "SIO-018", "SIO-019", "SIO-020", "SIO-021", "SIO-022", "SIO-023", "SIO-024", "SIO-025", "SIO-026", "SIO-027", "SIO-028", "SIO-029", "SIO-030", "SIO-031", "SIO-032", "SIO-033", "SIO-034", "SIO-035", "SIO-036", "SIO-037", "SIO-038", "SIO-039", "SIO-040", "SIO-041", "SIO-042", "SIO-043", "SIO-044", "SIO-045", "SIO-045A", "SIO-046", "SIO-047", "SIO-048", "SIO-049", "SIO-050"];
