#!/usr/bin/env python3
"""
The highlighter marks: twenty-four colour sets and one geometry, kept honest.

NOT the shipped logo — that is src/app/icon.svg, guarded by verify95-icons.py.

Dan, 2026-09-05: *"can we put the logo and 24 colors in the repo for posterity"*.
Nothing renders `HighlighterMark` yet — it is archival — which is precisely why it needs
a check. Code no page imports is code no reviewer opens and no screenshot
catches; the marks would rot in place with nobody able to tell that they had.

WHAT THIS PINS

  1  THE TWENTY-FOUR SETS, to the hex, in both tones.

  2  THE INVARIANT THAT MAKES THEM TWO TONES OF ONE THING. `deep` differs from
     `pale` in the tint and NOTHING else. That is what lets a mark be moved
     between the sets by editing one value; the moment a block or a mouth drifts
     apart, the two sets are twenty-four unrelated logos.

  3  EVERY RING CLEARS 5.1:1 ON THE CAHIER PAPER, recomputed here. The rings are
     the binding hardware and the smallest element; they were each generated by
     walking lightness down until they cleared that floor.

  4  DAN'S GEOMETRY BRIEF, as arithmetic rather than as prose:
       · *"less rounded edges"* — radius under 12% of the page width.
       · *"the roundedness should end before the first ring bind and start
         after the last"* — the top-left arc must finish above the first ring
         and the bottom-left arc begin below the last. At radius 9 the arc ends
         at y 17 and the first ring starts at 18.4; the last ends at 76.6 and
         the bottom arc begins at 83. Change the radius or move a ring and this
         is the assertion that notices.
       · *"the ring binds must eat into the cards"* — the knockout slot must be
         strictly larger than the ring, or the rings merely overlap the edge.

  5  THAT THE THREE BLOCKS STILL BUILD A C. Block and tint share a hue (they
     fuse into the stroke); the mouth sits opposite (it reads as the gap). If
     the mouth ever drifts toward the block's hue, the letter closes up and the
     mark quietly stops being a letter at all — which no compile error and no
     colour check would otherwise report.
"""

import math
import os
import re
import sys

PASS, FAIL = [], []


def ok(cond, good, bad):
    (PASS if cond else FAIL).append(good if cond else bad)


def read(p):
    return open(p, encoding="utf-8").read() if os.path.isfile(p) else ""


def lin(c):
    c /= 255
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def lum(h):
    h = h.lstrip("#")
    r, g, b = (int(h[i:i + 2], 16) for i in (0, 2, 4))
    return 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b)


def ratio(a, b):
    la, lb = lum(a), lum(b)
    hi, lo = max(la, lb), min(la, lb)
    return (hi + 0.05) / (lo + 0.05)


def hue(h):
    hx = h.lstrip("#")
    r, g, b = (lin(int(hx[i:i + 2], 16)) for i in (0, 2, 4))
    l_ = (0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b) ** (1 / 3)
    m_ = (0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b) ** (1 / 3)
    s_ = (0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b) ** (1 / 3)
    a = 1.9779984951 * l_ - 2.4285922050 * m_ + 0.4505937099 * s_
    bb = 0.0259040371 * l_ + 0.7827717662 * m_ - 0.8086757660 * s_
    return math.degrees(math.atan2(bb, a)) % 360


def apart(a, b):
    d = abs(a - b) % 360
    return min(d, 360 - d)


if not os.path.isfile("package.json"):
    print("run from the repo root")
    sys.exit(2)

SRC = read("src/content/highlighterMarks.ts")
PAPER = "#faf6ee"

# key -> (block, pale tint, deep tint, mouth, ring)
EXPECT = {
    "pink":       ("#ff4eb2", "#ffb9d9", "#d7008e", "#00b28b", "#c1007f"),
    "teal":       ("#00c197", "#00fbc6", "#009675", "#ff4eb2", "#00775c"),
    "orange":     ("#ff9037", "#ffddc7", "#d36d00", "#00a5e4", "#9f5100"),
    "sky":        ("#00b2f6", "#abe0ff", "#008bc1", "#ff9037", "#00709d"),
    "yellow":     ("#fcdf00", "#ffea6a", "#d0b800", "#8688ff", "#756700"),
    "periwinkle": ("#9398ff", "#cfd4ff", "#6d64ff", "#fcdf00", "#6045ff"),
    "green":      ("#00dd3e", "#b0ffb2", "#00b130", "#f005ff", "#007a1e"),
    "magenta":    ("#f350ff", "#fcbfff", "#cb00d9", "#00dd3e", "#b700c3"),
    "blue":       ("#1ca6ff", "#a9d7ff", "#0080ca", "#d78100", "#006baa"),
    "amber":      ("#e88c00", "#ffcd9c", "#b66c00", "#1ca6ff", "#985900"),
    "violet":     ("#b17eff", "#d9c6ff", "#9832ff", "#8ca600", "#9200fe"),
    "olive":      ("#98b300", "#c7ea00", "#768c00", "#b17eff", "#5e6f00"),
}

ok(bool(SRC), "src/content/highlighterMarks.ts is present",
   "src/content/highlighterMarks.ts is missing — the mark's colours live nowhere else")

# ---- 1 · the pale rows, parsed from the table ----------------------------
rows = {}
for m in re.finditer(
    r'key:\s*"([a-z]+)".*?block:\s*"(#[0-9a-f]{6})",\s*tint:\s*"(#[0-9a-f]{6})",'
    r'\s*mouth:\s*"(#[0-9a-f]{6})",\s*ring:\s*"(#[0-9a-f]{6})"', SRC, re.S
):
    rows[m.group(1)] = m.groups()[1:]

ok(len(rows) == 12,
   f"the pale set declares all 12 marks",
   f"found {len(rows)} mark rows, expected 12 — the table shape changed and this "
   "check has gone blind rather than found a fault")

wrong = []
for key, (block, pale, _deep, mouth, ring) in EXPECT.items():
    got = rows.get(key)
    if got is None:
        wrong.append(f"{key} missing")
    elif got != (block, pale, mouth, ring):
        wrong.append(f"{key} is {got}, expected {(block, pale, mouth, ring)}")
ok(not wrong,
   "every pale mark matches its recorded colours",
   "the pale set has drifted: " + "; ".join(wrong))

# ---- 2 · the deep set is the pale set with ONE value moved ----------------
deep_block = re.search(r"MARKS_DEEP[\s\S]*?\{([\s\S]*?)\}\[m\.key\]", SRC)
deep = dict(re.findall(r'([a-z]+):\s*"(#[0-9a-f]{6})"', deep_block.group(1))) if deep_block else {}
ok(len(deep) == 12,
   "the deep set overrides exactly 12 tints",
   f"the deep set overrides {len(deep)} tints, expected 12")
bad = [f"{k}: {deep.get(k)} != {v[2]}" for k, v in EXPECT.items() if deep.get(k) != v[2]]
ok(not bad, "and each deep tint is the recorded one", "deep tints drifted: " + "; ".join(bad))

# The structural claim, not just the values: deep is built FROM pale by spreading
# it, so block/mouth/ring cannot diverge. If someone rewrites this as a second
# literal table, that guarantee is gone even if today's values happen to match.
ok(re.search(r"MARKS_DEEP[^=]*=\s*MARKS_PALE\.map", SRC) is not None,
   "the deep set is derived from the pale set, so only the tint can differ",
   "MARKS_DEEP is no longer derived from MARKS_PALE. Written as its own literal "
   "table, a block or mouth can drift between the two sets and nothing will say "
   "so — they stop being two tones of one mark.")

# ---- 3 · the rings clear the paper ---------------------------------------
thin = [f"{k} {ratio(v[4], PAPER):.2f}" for k, v in EXPECT.items() if ratio(v[4], PAPER) < 5.10]
ok(not thin,
   f"every ring clears 5.1:1 on the Cahier paper "
   f"(worst {min(ratio(v[4], PAPER) for v in EXPECT.values()):.2f})",
   "a ring no longer clears 5.1:1 on paper: " + ", ".join(thin))

# ---- 4 · the block and the mouth stay opposite ---------------------------
close = [f"{k} {apart(hue(v[0]), hue(v[3])):.0f}°" for k, v in EXPECT.items()
         if apart(hue(v[0]), hue(v[3])) < 140]
ok(not close,
   "block and mouth stay opposite on the wheel in all 12 (≥ 140° apart)",
   "the mouth has drifted toward the block hue in " + ", ".join(close) +
   " — the mouth reads as a gap only because it leaves the family. Close that "
   "gap and the C stops being a letter.")

# and block/tint stay in the SAME family, in both tones
split = [k for k, v in EXPECT.items()
         if apart(hue(v[0]), hue(v[1])) > 25 or apart(hue(v[0]), hue(v[2])) > 25]
ok(not split,
   "and block and tint share a hue in both tones, so they fuse into one stroke",
   "block and tint no longer share a hue in " + ", ".join(split) +
   " — they must read as one colour or the C's top stroke detaches")

# ---- 5 · Dan's geometry brief, as arithmetic -----------------------------
def num(name, block=SRC):
    m = re.search(name + r"\s*:\s*([0-9.]+)", block)
    return float(m.group(1)) if m else None


page = re.search(r"page:\s*\{([^}]*)\}", SRC)
ring = re.search(r"ring:\s*\{([^}]*)\}", SRC)
py, ph, pr = (num(k, page.group(1)) for k in ("y", "h", "r")) if page else (None, None, None)
pw = num("w", page.group(1)) if page else None
tops = [float(t) for t in re.findall(r"[0-9.]+", re.search(r"tops:\s*\[([^\]]*)\]", SRC).group(1))] \
    if re.search(r"tops:\s*\[", SRC) else []
rh = num("h", ring.group(1)) if ring else None
bite = num("bite")

ok(None not in (py, ph, pr, pw, rh, bite) and len(tops) == 4,
   "the geometry constants are all present",
   "MARK_GEOMETRY is missing a value this check needs — the shape changed")

if None not in (py, ph, pr, pw, rh, bite) and len(tops) == 4:
    ok(pr / pw < 0.12,
       f"the corners are squarer than an eighth of the page ({pr}/{pw} = {pr / pw:.2f})",
       f"the corner radius is {pr / pw:.2f} of the page width. Dan asked for LESS "
       "rounded than the original; over 0.12 walks that back.")
    arc_end, arc_start = py + pr, py + ph - pr
    ok(arc_end < tops[0],
       f"the top-left rounding ends at y {arc_end:g}, above the first ring at {tops[0]:g}",
       f"the top-left arc runs to y {arc_end:g} but the first ring starts at {tops[0]:g}. "
       "Dan: the roundedness should end BEFORE the first ring bind.")
    last_end = tops[-1] + rh
    ok(arc_start > last_end,
       f"and the bottom-left rounding starts at y {arc_start:g}, below the last ring "
       f"at {last_end:g}",
       f"the bottom-left arc begins at y {arc_start:g} but the last ring ends at "
       f"{last_end:g}. Dan: it should start AFTER the last ring bind.")
    ok(bite > 0,
       f"and the rings bite {bite:g} units into the page on every side",
       "the knockout slot is not larger than the ring, so the rings sit beside the "
       "page rather than eating into it (Dan: the ring binds must eat into the cards)")

print("\n".join("  ok    " + m for m in PASS))
if FAIL:
    print("\n".join("  FAIL  " + m for m in FAIL))
    print("-" * 70)
    print(f"  {len(PASS)} passed · {len(FAIL)} failed")
    sys.exit(1)
print("-" * 70)
print(f"  all {len(PASS)} checks passed")
