"""CEFR Can-Do descriptors for LAF1201 SIOs."""

CEFR_HEADERS = ["CEFR Mode", "Can-Do (A1)", "Linguistic competence (measurable)"]

# Keyed by SIO # — aligned to upload order/content (Unité 0 reorder: 006 nouns, 007 numbers,
# 008 question words, 009 classroom, 010 greetings).
CEFR = {
    "SIO-001": ("Spoken Interaction",
        "I can introduce myself and other people, ask someone their name, and address someone politely with M./Mme, using simple set phrases, as long as the other person speaks slowly and clearly and is ready to help.",
        "Conjugate s'appeler in all 6 persons (≥5/6); ask a name with tu and with vous; introduce a third person (Il/Elle s'appelle…); use M./Mme as a form of address."),
    "SIO-002": ("Spoken Interaction",
        "I can choose how formally to address one or more people in simple, everyday social situations.",
        "Select tu / vous (polite sg) / vous (pl) correctly in ≥10/12 situations; give a one-phrase reason for each choice."),
    "SIO-003": ("Spoken Interaction",
        "I can spell out my name and simple words aloud and ask someone how a word is spelled (Comment ça s'écrit ?).",
        "Name all 26 letters; sort them into the 7 vowel-sound groups; spell a given word aloud (≥90% letters correct)."),
    "SIO-004": ("Spoken Interaction",
        "I can say and ask on which day and at what time of day something happens, using simple expressions.",
        "List the 7 days in order and the 3 moments of the day; label a day as weekday/weekend; ask and answer C'est quand ?"),
    "SIO-005": ("Spoken Production",
        "I can name basic colours to describe and identify familiar things.",
        "Name the 12 colours; give the matching mnemonic object for each (≥10/12)."),
    "SIO-006": ("Spoken Production",
        "I can name common people and classroom objects with the correct article.",
        "Label the 14 core nouns with un/une (≥12/14)."),
    "SIO-007": ("Spoken Interaction",
        "I can understand and say numbers up to 20 and ask and tell how many there are, provided people speak slowly.",
        "Read aloud any number 0–20; identify 17–19 as composites (dix-sept = 10 + 7); say 20; answer C'est combien ?"),
    "SIO-008": ("Spoken Interaction",
        "I can ask for basic information about something using simple C'est ___ ? questions.",
        "Build a correct C'est ___ ? question with each of the 6 question words (où/quand/combien/comment/quoi/qui) (6/6)."),
    "SIO-009": ("Listening",
        "I can follow short, simple classroom instructions delivered slowly, and ask what to do.",
        "Perform the correct action for the 9 instructions (≥8/9); ask On fait quoi ?"),
    "SIO-010": ("Spoken Interaction",
        "I can greet people and take my leave appropriately for the time of day and how well I know them.",
        "Produce the register-appropriate greeting/leave-taking for a given time and relationship (≥8/10); sort phrases into meeting vs parting and universal vs familiar."),
    "SIO-011": ("Spoken Production",
        "I can highlight who I am talking about using the right pronoun in simple sentences.",
        "Match each of the 8 subject pronouns to its stress pronoun; sort stress pronouns into subject-only / stress-only / either (≥7/8)."),
    "SIO-012": ("Spoken Production",
        "I can say who someone is and give basic information about people, making the form agree for gender and number.",
        "Conjugate être in all 8 persons (≥7/8); apply m/f and sg/pl agreement to étudiant(e)(s)."),
    "SIO-013": ("Spoken Production",
        "I can say what job someone has.",
        "Name 10 professions in m/f forms; present a person with il est/elle est or C'est un/une ___ (≥8/10)."),
    "SIO-014": ("Spoken Interaction",
        "I can say and ask what someone is studying.",
        "Name academic subjects with the correct article; answer Qu'est-ce que tu étudies ? with Je suis étudiant(e) en ___."),
    "SIO-015": ("Spoken Production",
        "I can name countries with the correct article and ask which country something is.",
        "Label 25 countries with le/la/l'/les (∅ where invariable) (≥80%); ask C'est quel pays ?"),
    "SIO-016": ("Spoken Production",
        "I can say what nationality someone is, using the correct form.",
        "Produce all 4 nationality-adjective forms for each of the 25 countries; match country → nationality (≥80%)."),
    "SIO-017": ("Spoken Production",
        "I can say which language(s) are spoken in a given country.",
        "Match each of the 25 countries to its main language(s) (≥80%)."),
    "SIO-018": ("Spoken Interaction",
        "I can understand and say numbers from 20 to 69 in simple exchanges (ages, prices, quantities).",
        "Read aloud any number 20–69; identify the 6 tens; build composites 21–69 with et un where required (≥90%)."),
    "SIO-019": ("Spoken Interaction",
        "I can say my age and how I feel, in the affirmative and the negative.",
        "Conjugate avoir (≥7/8); give age (J'ai ___ ans); express the 4 states; sort 6 states into être vs avoir (≥5/6); produce affirmative and negative forms."),
    "SIO-020": ("Written Production",
        "I can write a few simple sentences about a francophone country I know, if I can prepare.",
        "Write 3–4 comprehensible sentences with all 4 elements present (name, location, language, one cultural fact)."),
    "SIO-021": ("Spoken Production",
        "I can point out and name objects and people and ask what something is.",
        "Present ≥6 items with c'est + un/une and ce sont + des; ask C'est quoi ?"),
    "SIO-022": ("Spoken Production",
        "I can say what things and activities I like.",
        "Conjugate aimer in all persons; produce aimer + definite article + N and aimer + infinitive (≥2 each)."),
    "SIO-023": ("Spoken Production",
        "I can say what sports and activities I do.",
        "Produce faire + du/de la/de l'/des with the correct contraction for ≥6 activities (≥80%)."),
    "SIO-024": ("Spoken Production",
        "I can say where I go.",
        "Produce aller + au/à la/à l'/aux with the correct contraction for ≥6 destinations (≥80%)."),
    "SIO-025": ("Spoken Production",
        "I can say what belongs to me and to others.",
        "Select the correct possessive (mon/ma/mes … son/sa/ses, + notre/votre/leur) by the noun's gender/number for ≥8 prompts (≥80%)."),
    "SIO-026": ("Spoken Production",
        "I can say when I do my regular activities.",
        "Use le + day, le week-end, tous les…, and à + time for ≥5 prompts; sort into day/frequency/clock."),
    "SIO-027": ("Spoken Production",
        "I can say who I do things with, or that I do them alone.",
        "Use avec + stress pronoun/noun and seul(e) for ≥5 prompts."),
    "SIO-028": ("Spoken Interaction",
        "I can ask why and give a simple reason for a preference.",
        "Answer Pourquoi ? with parce que c'est + adjective or parce que j'aime + N for ≥3 prompts."),
    "SIO-029": ("Spoken Interaction",
        "I can invite someone and accept, refuse, or suggest another time, using set phrases.",
        "Use vouloir/pouvoir to perform all 4 functions (inviter/accepter/refuser/reporter) in a short dialogue."),
    "SIO-030": ("Written Production",
        "I can write a short, friendly message with good wishes and simple linking words, if I can prepare.",
        "Produce well-wish formulas; write a 4–6 sentence email using ≥3 connectors (d'abord/ensuite/aussi/mais/et/enfin) correctly."),
    "SIO-031": ("Spoken Interaction",
        "I can talk about and ask about today's weather in simple terms.",
        "Describe the weather with ≥6 expressions (≥80%); ask Quel temps fait-il ?"),
    "SIO-032": ("Spoken Production",
        "I can say which country I am in, going to, or coming from.",
        "Use en/au/aux/à with être/aller/venir in ≥6 sentences (≥80%)."),
    "SIO-033": ("Spoken Production",
        "I can say where I am, where I am going, and where I am coming from around town.",
        "Use être/aller/venir + contraction (au/à la/à l'/aux, du/de la/de l') in ≥6 sentences (≥80%)."),
    "SIO-034": ("Spoken Production",
        "I can say where a place is in relation to another one.",
        "Use the spatial prepositions (à côté de, en face de, près de, loin de) + correct contraction for ≥4 prompts."),
    "SIO-035": ("Spoken Interaction",
        "I can ask simple yes/no and open questions to get the information I need.",
        "Form a yes/no question with Est-ce que…?; form an open question with each of the 7 question words (≥80%)."),
    "SIO-036": ("Spoken Interaction",
        "I can ask for and give simple directions to a place, without using commands.",
        "Give directions with c'est + preposition / il faut + infinitive / on + present; use ordinals premier–dixième correctly in ≥4 prompts (≥80%)."),
    "SIO-037": ("Spoken Interaction",
        "I can say what is possible or allowed in a place and ask for permission.",
        "Conjugate pouvoir (key persons); produce ≥3 on peut / je peux / vous pouvez + infinitive statements."),
    "SIO-038": ("Spoken Interaction",
        "I can ask how someone travels somewhere and say how I get there.",
        "Ask Comment tu vas à…?; answer with prendre + transport; use the pronoun y in ≥3 sentences."),
    "SIO-039": ("Spoken Interaction",
        "I can express what I want and need politely.",
        "Use je voudrais / j'aimerais / j'ai besoin de / je veux + noun or infinitive (all 4)."),
    "SIO-040": ("Spoken Production",
        "I can explain step by step how to get somewhere, linking the steps in order.",
        "Describe ≥4 ordered steps using d'abord/puis/ensuite/après/enfin with il faut + inf / on + present and transport + direction vocabulary."),
    "SIO-041": ("Spoken Production",
        "I can say what I eat and drink at each meal.",
        "Name the 4 meals and ≥2 foods/drinks each; say what I eat/drink (≥80%)."),
    "SIO-042": ("Spoken Production",
        "I can talk about food both in general and in the quantities I eat.",
        "Choose definite vs partitive correctly (J'aime le… vs Je mange du…) in ≥8 prompts (≥80%)."),
    "SIO-043": ("Spoken Production",
        "I can say what I do not eat or drink.",
        "Rewrite ≥5 affirmative food sentences into the negative with de/d' (≥80%)."),
    "SIO-044": ("Spoken Production",
        "I can say what people eat and drink.",
        "Conjugate manger and boire in all persons (≥7/8 each); use with foods/drinks."),
    "SIO-045": ("Spoken Production",
        "I can say how often I do everyday things.",
        "Place the 5 frequency adverbs correctly relative to the verb in ≥5 sentences; order them on a frequency scale."),
    "SIO-046": ("Spoken Production",
        "I can point out specific items (this/these) when shopping or ordering.",
        "Select ce/cet/cette/ces correctly by gender/number for ≥8 nouns (≥80%)."),
    "SIO-047": ("Spoken Interaction",
        "I can shop for food, ask the price, and ask for what I want politely.",
        "Match ≥5 shops to what they sell; say where I shop; ask Combien ça coûte ? / Je voudrais ___, s'il vous plaît."),
    "SIO-048": ("Spoken Production",
        "I can talk about plans, ability, obligation, and necessity in simple sentences.",
        "Use aller/pouvoir/devoir/falloir + infinitive with the correct meaning (one each)."),
    "SIO-049": ("Spoken Production",
        "I can give a simple opinion about a restaurant, mentioning good and bad points.",
        "State ≥1 positive point, ≥1 negative point, and a clear recommendation (Je recommande / Je ne recommande pas)."),
    "SIO-050": ("Spoken Interaction",
        "I can get by in a simple restaurant visit from arrival to paying, using set phrases, as long as staff are patient.",
        "Complete all 6 steps: greet, read the menu, order (entrée/plat/boisson/dessert), interact, ask for the bill, pay and say goodbye."),
}